steps:
  # Step to set up Docker Compose
  - name: "docker/compose:latest"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        export POSTGRES_USER=${_POSTGRES_USER}
        export POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}
        export POSTGRES_DB=${_POSTGRES_DB}
        export AWS_ACCESS_KEY_ID=${_AWS_ACCESS_KEY_ID}
        export AWS_SECRET_ACCESS_KEY=${_AWS_SECRET_ACCESS_KEY}
        docker-compose up --build -d

# Specify any required substitutions or environment variables
substitutions:
  _POSTGRES_USER: POSTGRES_USER
  _POSTGRES_PASSWORD: POSTGRES_PASSWORD
  _POSTGRES_DB: POSTGRES_DB
  _AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  _AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY

# Optionally, specify any secrets or additional configurations
availableSecrets:
  secretManager:
    - versionName: projects/river-tiger-440210-m6/secrets/POSTGRES_USER/versions/latest
      env: "POSTGRES_USER"
    - versionName: projects/river-tiger-440210-m6/secrets/POSTGRES_PASSWORD/versions/latest
      env: "POSTGRES_PASSWORD"
    - versionName: projects/river-tiger-440210-m6/secrets/POSTGRES_DB/versions/latest
      env: "POSTGRES_DB"
    - versionName: projects/river-tiger-440210-m6/secrets/AWS_ACCESS_KEY_ID/versions/latest
      env: "AWS_ACCESS_KEY_ID"
    - versionName: projects/river-tiger-440210-m6/secrets/AWS_SECRET_ACCESS_KEY/versions/latest
      env: "AWS_SECRET_ACCESS_KEY"
