version: "3.9"

services:
#################################
# Database
#################################
  db:
    container_name: db
    build: ./backend/database
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal_network
#################################
# Authentication
#################################
  authentication:
    container_name: authentication
    build: ./backend/authentication
    ports: 
      - "5001:5001"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PYTHONUNBUFFERED: 1
    networks:
      - internal_network
      
#################################
# Requests
#################################
  requests:
    container_name: requests
    build: ./backend/requests
    ports: 
      - "5002:5002"
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - internal_network

#################################
# RabbitMQ 
#################################
  rabbitmq:
    container_name: amqp
    build: ./backend/amqp
    ports:
      - "15672:15672"  # Expose RabbitMQ management interface
      - "5672:5672"    # Expose RabbitMQ main port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      
    networks:
      - internal_network
#################################
# Emailing service
#################################
  emailing:
    build: ./backend/emailing
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - internal_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      REQUESTS_API_URL: ${REQUESTS_API_URL}
      SCHEDULE_API_URL: ${SCHEDULE_API_URL}
      AUTH_API_URL: ${AUTH_API_URL}
    networks:
      - internal_network


volumes:
  pgdata:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  internal_network:
    driver: bridge