
import {
    AlertTriangle,
    ArrowRight,
    Calendar,
    Calendar1,
    CalendarDays,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FilePlus,
    FileText,
    HelpCircle,
    House,
    Image,
    Laptop,
    Loader2,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Settings,
    SunMedium,
    Trash,
    User,
    Users,
    X,
  } from "lucide-react"
  
  
  export const Icons: any = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    check: Check,
    home: House,
    user: User,
    users: Users,
    filePlus: FilePlus,
    calendar: Calendar,
    calendar1: Calendar1,
    calendarDays: CalendarDays,
  }
